version: 0.2

phases:
  build:
    commands:
      - ls
      - docker build -t devsnest20/peer_droid .
      - docker login --username=${username} --password=${password}
      - docker push devsnest20/peer_droid 