version: 0.2

phases:
  build:
    commands:
      - ls
      - docker build -t prachipathrayan/peerlearn .
      - docker login --username=${username} --password=${password}
      - docker push prachipathrayan/peerlearn