API_ENDPOINTS = {
    "SUBMISSIONS": "/api/v1/submissions",
    "CONTENTS": "/api/v1/contents",
    "USER_REPORT": "/api/v1/users/report",
    "USERS": "/api/v1/users",
    "USER_LEFT_DISCORD": "/api/v1/users/left_discord",
    "GET_TOKEN": "/api/v1/users/get_token",
    "WRITEUPS": "/api/v1/writeups",
    "GROUP_CALLS": "/api/v1/groupcalls",
    "MMTS": "/api/v1/mmts",
    "UPDATE_USER_GROUP": "/api/v1/group-members/update_user_group",
    "DELETE_GROUP": "/api/v1/groups/delete_group",
    "UPDATE_GROUP_NAME": "/api/v1/groups/update_group_name",
    "UPDATE_GROUP_BATCHLEADER": "/api/v1/groups/update_batch_leader",
    "UPDATE_USER_DISCORD_NAME": "/api/v1/users/update_discord_username",
    "NOTIFICATION_BOT": "/api/v1/notification-bot/",
    "CHECK_GROUP_NAME": "/api/v1/users/check_group_name",
    "SERVER_GROUP": "/api/v1/groups/server_details",
    "ASSIGN_SERVER": "/api/v1/server-users",
    "CHECK_GROUP_DETAILS": "/api/v1/groups/team_details",
    "CHECK_USER_DETAILS": "/api/v1/users/check_user_details",
    "ACTIVE_GROUPS": "/api/v1/scrums/weekly_leaderboard",
    "GROUPS_DATA": "/api/v1/groups/weekly_group_data",
}
